server:
  port: 8888
spring:
  application:
    name: jiayou-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_route
          uri: http://localhost:8888
          predicates:
            - Path=/api/**
          filter:
            - StripPrefix=1
            - Post
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
#        - id: payment_routh
          #匹配后提供服务的路由地址
#          uri: http://news.baidu.com
#          predicates:
            #断言,路径相匹配的进行路由
#            - Path= /guonei/**
#        - id: circuitbreaker_route
#          uri: http://news.baidu.com
#          predicates:
#            - Path= /guonei/**
#          filters:
#            - Hystrix=myCommandName
        - id: ratelimiter_route
          uri: http://news.baidu.com
          predicates:
            - Path= /guonei/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
#                key-resolver: "#{@userKeyResolver}"



eureka:
  instance:
    #eureka客户端的实例名字（主机名）
    hostname: gateway-service
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      #表示向注册中心注册自己
      register-with-eureka: true
      #表示需要去注册中心检索服务
      fetch-registry: true
      #与eureka server交互的地址，包括查询服务和注册服务
      defaultZone: http://localhost:8761/eureka
